version: '3.8'

services:
  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306"
    expose:
      - '3306'
    volumes:
      - mysql-volume:/var/run/mysqld/
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
  web:
    build: .
    command: bash -c "python link_shortener//manage.py migrate
             && python link_shortener//manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - mysql-volume:/var/run/mysqld/
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    env_file:
      - .env
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web


volumes:
    mysql-volume:



