# Generated by Django 3.2.5 on 2021-08-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkreferences',
            name='short_link',
            field=models.CharField(default='', max_length=8),
        ),
    ]
