# Generated by Django 3.2.5 on 2021-08-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener_app', '0002_linkreferences_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkreferences',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
