# Generated by Django 3.2.5 on 2021-09-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener_app', '0003_alter_linkreferences_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
            ],
        ),
    ]
