# Generated by Django 3.2.5 on 2021-09-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener_app', '0004_userdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='RegistrationForm',
        ),
    ]
