# Generated by Django 3.2.5 on 2021-09-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener_app', '0005_rename_userdata_registrationform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationForm',
            new_name='UserData',
        ),
    ]
