# Generated by Django 3.2.5 on 2022-02-17 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener_app', '0008_verificationcodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcodes',
            name='email',
        ),
        migrations.AddField(
            model_name='linkreferences',
            name='clicker_ip_tracker_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linkreferences',
            name='clicks',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='linkreferences',
            name='clicks_counter_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linkreferences',
            name='creation_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='linkreferences',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='link_shortener_app.userdata'),
        ),
        migrations.AddField(
            model_name='verificationcodes',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='link_shortener_app.userdata'),
        ),
        migrations.CreateModel(
            name='ClickerIPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('link', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='link_shortener_app.linkreferences')),
            ],
        ),
    ]
