# Generated by Django 3.2.5 on 2022-02-17 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener_app', '0009_auto_20220217_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkreferences',
            name='creation_date',
            field=models.DateField(default=datetime.date(2022, 2, 17)),
        ),
        migrations.AlterField(
            model_name='linkreferences',
            name='link',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='linkreferences',
            name='short_link',
            field=models.SlugField(default='', max_length=8),
        ),
    ]
