# Generated by Django 3.2.5 on 2022-02-17 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener_app', '0010_auto_20220217_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkreferences',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 17, 18, 55, 23, 874107, tzinfo=utc)),
        ),
    ]
