# Generated by Django 3.2.5 on 2022-02-18 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener_app', '0012_alter_linkreferences_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkreferences',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
