# Generated by Django 3.2.5 on 2022-02-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener_app', '0013_alter_linkreferences_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkreferences',
            name='clicks',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
