"""
Django settings for link_shortener project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

dotenv_path = os.path.join(BASE_DIR.parent, '.env')  # .env file excepted in the most top-level file
if os.path.exists(dotenv_path):
    load_dotenv(dotenv_path)
else:
    raise EnvironmentError('No Env File Provided')

DB_TYPE = os.environ.get('DB_TYPE')  # ='mysql'
DB_PATH = os.environ.get('DB_PATH')  # ='dbpath/myDB'
DB_USER = os.environ.get('DB_USER')  # ='root'
DB_PASSWORD = os.environ.get('DB_PASSWORD')  # ='root'
DB_HOST = os.environ.get('DB_HOST')  # ='localhost'
DB_PORT = os.environ.get('DB_PORT')  # ='3306'
SHORT_LINK_LEN = os.environ.get('SHORT_LINK_LEN')  # ='6'
# length of your shortlink e.g. with 4 you generate 4 symbols
SITE_DOMAIN_NAME = os.environ.get('SITE_DOMAIN_NAME')  # ='http://mysite.com/here_we_land'
SECRET_KEY = os.environ.get('SECRET_KEY')  # ='django-secret_key'

DB_ENGINE = 'django.db.backends.' + DB_TYPE

OFFICIAL_EMAIL = os.environ.get('OFFICIAL_EMAIL')  # ='companymail@mail.com'
EMAIL_HOST = os.environ.get('EMAIL_HOST')  # ='smtp.mail.com'
EMAIL_PORT = os.environ.get('EMAIL_PORT')  # ='587'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')  # ='mail@mail.com'
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')  # ='my.password'

# Build paths inside the project like this: BASE_DIR / 'subdir'.

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'link_shortener_app.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'link_shortener.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'link_shortener.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': DB_PATH,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
